RU language readme (Re PR)
AyuGram/AyuGramDesktop pull request #19
Opened 2024-09-12 16:40 UTC by kaeeraa

2024-09-12 21:00 UTC, ZavaruKitsu requested changes
Перечитай файл внимательно

2024-09-12 21:00 UTC, ZavaruKitsu commented on README-ru.md
> +
remove empty line at the top
rename to `README-RU.md`

2024-09-12 21:00 UTC, ZavaruKitsu commented on README-ru.md
> +#### Само-сборка
Ручная сборка или чето в этом стиле

2024-09-12 21:00 UTC, ZavaruKitsu commented on README-ru.md
> +Следуйте [оффициальному руководству](https://github.com/AyuGram/AyuGramDesktop/blob/dev/docs/building-win-x64.md) если вы хотите
оффициальному -> официальному

2024-09-12 21:00 UTC, ZavaruKitsu commented on README-ru.md
![image](https://github.com/user-attachments/assets/883f23e0-0ea7-4361-b24d-6c45469fe2d2)

2024-09-13 05:17 UTC, kaeeraa commented on README-ru.md
![static-assets-upload8898329607101416812.png](https://github.com/user-attachments/assets/ffac7849-978a-4862-95d2-fd6650060e87)

2024-09-19 22:26 UTC, Goosegit11 commented
анус

2024-09-27 19:09 UTC, merged